enum Strings {
    static let ko: [String: String] = [
        "Add your Soniox API key in Settings first.": "먼저 설정에서 Soniox API 키를 추가하세요.",
        "Add your Soniox API key to start.": "시작하려면 Soniox API 키를 추가하세요.",
        "and": "언어 B",
        "API key": "API 키",
        "Auto": "자동",
        "Between": "언어 A",
        "Bigger / Smaller Text": "글자 크게 / 작게",
        "Bigger Text": "글자 크게",
        "Caption appearance": "자막 모양",
        "Captions": "자막",
        "Captions locked · ⌃⌥L to unlock": "자막 잠김 · ⌃⌥L로 해제",
        "Captions unlocked": "자막 잠금 해제됨",
        "Change languages from the globe button while listening.": "듣는 중에도 지구본 버튼에서 언어를 바꿀 수 있습니다.",
        "Clear": "투명",
        "Connect Soniox": "Soniox 연결",
        "Connecting…": "연결 중…",
        "Connection lost: %@": "연결이 끊겼습니다: %@",
        "Context": "컨텍스트",
        "Couldn’t capture system audio (%d).": "시스템 오디오를 캡처할 수 없습니다 (%d).",
        "Dark": "어둡게",
        "Detect automatically": "자동 감지",
        "Drag the caption’s top or bottom edge to add lines, its sides to resize. Drop it near the center and it snaps.": "자막의 위아래 가장자리를 끌면 줄 수가, 양옆을 끌면 너비가 바뀝니다. 화면 가운데 근처에 놓으면 중앙에 맞춰집니다.",
        "Export…": "내보내기…",
        "Export Transcript…": "대화록 내보내기…",
        "Fewer Caption Lines": "자막 줄 줄이기",
        "For conversations: each side is translated into the other’s language.": "대화용: 양쪽이 서로의 언어로 번역됩니다.",
        "From": "원문",
        "General": "일반",
        "Get a key at console.soniox.com": "console.soniox.com에서 키 발급",
        "Glass": "글래스",
        "Helps recognition of names and terms. Applies from the next session.": "이름과 용어 인식에 도움이 됩니다. 다음 세션부터 적용됩니다.",
        "Hide Captions": "자막 숨기기",
        "Hide Transcript": "대화록 숨기기",
        "Interface language": "인터페이스 언어",
        "Jump to Live": "실시간으로 이동",
        "Keep Captions on Top": "자막 항상 위에",
        "Keep on Top": "항상 위에",
        "Language": "언어",
        "Languages": "언어",
        "Lines": "줄 수",
        "Listen": "듣기",
        "Listen to": "입력",
        "Listening": "듣는 중",
        "Listening…": "듣는 중…",
        "Lock Captions": "자막 잠그기",
        "Lock captions (click-through)": "자막 잠그기 (클릭 통과)",
        "Mac Audio": "Mac 오디오",
        "Mac Audio + Microphone": "Mac 오디오 + 마이크",
        "Merge when one voice was split into two speakers.": "한 사람이 두 화자로 나뉘었을 때 합치세요.",
        "Microphone": "마이크",
        "Microphone access is off. Turn it on in System Settings › Privacy & Security.": "마이크 접근이 꺼져 있습니다. 시스템 설정 › 개인정보 보호 및 보안에서 켜세요.",
        "Mode": "모드",
        "Model": "모델",
        "More / Fewer Caption Lines": "자막 줄 늘리기 / 줄이기",
        "More Caption Lines": "자막 줄 늘리기",
        "Names, topics, jargon…": "이름, 주제, 전문 용어…",
        "New Session": "새 세션",
        "No microphone found.": "마이크를 찾을 수 없습니다.",
        "No one has spoken yet.": "아직 말한 사람이 없습니다.",
        "Open Settings…": "설정 열기…",
        "Paste a Soniox API key to start. It’s stored encrypted on this Mac.": "Soniox API 키를 붙여 넣으세요. 이 Mac에 암호화되어 저장됩니다.",
        "Pause": "일시정지",
        "Paused": "일시정지됨",
        "Quit Luka": "Luka 종료",
        "Ready": "준비됨",
        "Ready when you are": "준비됐습니다",
        "Reconnecting…": "다시 연결 중…",
        "Rename Current Speaker…": "지금 말하는 사람 이름 바꾸기…",
        "Rename speaker": "화자 이름 바꾸기",
        "Resume": "계속",
        "Same person as…": "같은 사람으로 합치기…",
        "Save": "저장",
        "Settings…": "설정…",
        "Shortcuts": "단축키",
        "Show Captions": "자막 보기",
        "Show Original": "원문 보기",
        "Show Transcript": "대화록 보기",
        "Smaller Text": "글자 작게",
        "Soniox didn’t accept the settings: %@": "Soniox가 설정을 받아들이지 않았습니다: %@",
        "Soniox is rate limiting this key. Try again in a moment.": "요청이 너무 많습니다. 잠시 후 다시 시도하세요.",
        "Soniox rejected the API key.": "Soniox가 API 키를 거부했습니다.",
        "Speaker %d": "화자 %d",
        "Speakers": "화자",
        "Speakers appear here as they talk.": "말하는 사람이 여기에 나타납니다.",
        "Speech in any language is translated into one language.": "어떤 언어로 말해도 한 언어로 번역합니다.",
        "Start / Pause": "시작 / 일시정지",
        "Start Listening": "듣기 시작",
        "Style": "스타일",
        "Luka listens to your Mac and writes down every speaker, translated as they talk.": "Luka가 Mac의 소리를 듣고, 말하는 사람별로 받아 적으며 실시간으로 번역합니다.",
        "System": "시스템",
        "Text size": "글자 크기",
        "To": "번역",
        "Transcribe": "받아쓰기",
        "Transcript": "대화록",
        "Translate": "번역",
        "Try Again": "다시 시도",
        "Two-way": "양방향",
        "Writes down what’s said, without translating.": "번역 없이 말한 내용만 받아 적습니다.",
        "Your Soniox account is out of credits.": "Soniox 크레딧이 부족합니다.",
        "Back to Live Session": "실시간 세션으로 돌아가기",
        "Continue": "이어서 듣기",
        "Copied transcript": "대화록을 복사했습니다",
        "Copy Transcript": "대화록 복사",
        "Delete": "삭제",
        "Delete Line": "줄 삭제",
        "Delete Session…": "세션 삭제…",
        "Delete this session?": "이 세션을 삭제할까요?",
        "Delete…": "삭제…",
        "Edit": "편집",
        "Edit transcript": "대화록 편집",
        "Finish Session": "세션 끝내기",
        "Finish the session to edit": "세션을 끝내면 편집할 수 있습니다",
        "In Luka": "Luka 안에서",
        "Lock / unlock captions": "자막 잠금 / 해제",
        "Luka keeps running in the menu bar, so ⌃⌥N can start a transcription at any time.": "Luka는 메뉴 막대에서 계속 실행되므로 언제든 ⌃⌥N으로 받아쓰기를 시작할 수 있습니다.",
        "More": "더 보기",
        "Name whoever is speaking": "지금 말하는 사람 이름 짓기",
        "New Transcription": "새 받아쓰기",
        "New transcription": "새 받아쓰기",
        "No Session": "세션 없음",
        "Nothing yet": "아직 내용 없음",
        "Open at login": "로그인 시 열기",
        "Open transcript": "대화록 열기",
        "Rename…": "이름 변경…",
        "Show / hide captions": "자막 보기 / 숨기기",
        "Show / hide transcript": "대화록 보기 / 숨기기",
        "Show in Dock": "Dock에 표시",
        "The transcript will be removed from this Mac.": "이 Mac에서 대화록이 삭제됩니다.",
        "Title": "제목",
        "Today": "오늘",
        "Unlock": "잠금 해제",
        "Works from any app": "어느 앱에서나",
        "Yesterday": "어제",
        "from any app": "어느 앱에서나",
        "Swap": "서로 바꾸기",
        "Show captions": "자막 표시",
        "While listening": "듣는 동안만",
        "Always": "항상",
        "Captions fade in when Luka starts listening and out when you finish. ⌃⌥C hides or shows them anytime.": "듣기를 시작하면 자막이 나타나고, 끝내면 사라집니다. ⌃⌥C로 언제든 숨기거나 보일 수 있습니다.",
        "Captions stay until you hide them with ⌃⌥C.": "⌃⌥C로 숨길 때까지 자막이 계속 표시됩니다.",
    ]

    static let zh: [String: String] = [
        "Add your Soniox API key in Settings first.": "请先在设置中添加 Soniox API 密钥。",
        "Add your Soniox API key to start.": "添加 Soniox API 密钥即可开始。",
        "and": "语言 B",
        "API key": "API 密钥",
        "Auto": "自动",
        "Between": "语言 A",
        "Bigger / Smaller Text": "放大 / 缩小文字",
        "Bigger Text": "放大文字",
        "Caption appearance": "字幕外观",
        "Captions": "字幕",
        "Captions locked · ⌃⌥L to unlock": "字幕已锁定 · 按 ⌃⌥L 解锁",
        "Captions unlocked": "字幕已解锁",
        "Change languages from the globe button while listening.": "收听时也可以通过地球按钮切换语言。",
        "Clear": "透明",
        "Connect Soniox": "连接 Soniox",
        "Connecting…": "正在连接…",
        "Connection lost: %@": "连接已断开：%@",
        "Context": "上下文",
        "Couldn’t capture system audio (%d).": "无法捕获系统音频（%d）。",
        "Dark": "深色",
        "Detect automatically": "自动检测",
        "Drag the caption’s top or bottom edge to add lines, its sides to resize. Drop it near the center and it snaps.": "拖动字幕的上下边缘可增减行数，拖动两侧可调整宽度。放在屏幕中央附近会自动居中。",
        "Export…": "导出…",
        "Export Transcript…": "导出记录…",
        "Fewer Caption Lines": "减少字幕行数",
        "For conversations: each side is translated into the other’s language.": "适用于对话：双方的话会译成对方的语言。",
        "From": "源语言",
        "General": "通用",
        "Get a key at console.soniox.com": "在 console.soniox.com 获取密钥",
        "Glass": "玻璃",
        "Helps recognition of names and terms. Applies from the next session.": "有助于识别人名和术语。下次会话起生效。",
        "Hide Captions": "隐藏字幕",
        "Hide Transcript": "隐藏记录",
        "Interface language": "界面语言",
        "Jump to Live": "回到实时",
        "Keep Captions on Top": "字幕置顶",
        "Keep on Top": "置顶",
        "Language": "语言",
        "Languages": "语言",
        "Lines": "行数",
        "Listen": "收听",
        "Listen to": "音频来源",
        "Listening": "正在收听",
        "Listening…": "正在收听…",
        "Lock Captions": "锁定字幕",
        "Lock captions (click-through)": "锁定字幕（点击穿透）",
        "Mac Audio": "Mac 音频",
        "Mac Audio + Microphone": "Mac 音频 + 麦克风",
        "Merge when one voice was split into two speakers.": "同一个人被识别成两位说话人时，可以合并。",
        "Microphone": "麦克风",
        "Microphone access is off. Turn it on in System Settings › Privacy & Security.": "麦克风权限已关闭。请在“系统设置 › 隐私与安全性”中开启。",
        "Mode": "模式",
        "Model": "模型",
        "More / Fewer Caption Lines": "增加 / 减少字幕行数",
        "More Caption Lines": "增加字幕行数",
        "Names, topics, jargon…": "人名、话题、术语…",
        "New Session": "新会话",
        "No microphone found.": "未找到麦克风。",
        "No one has spoken yet.": "还没有人说话。",
        "Open Settings…": "打开设置…",
        "Paste a Soniox API key to start. It’s stored encrypted on this Mac.": "粘贴 Soniox API 密钥即可开始，密钥会加密保存在这台 Mac 上。",
        "Pause": "暂停",
        "Paused": "已暂停",
        "Quit Luka": "退出 Luka",
        "Ready": "就绪",
        "Ready when you are": "随时可以开始",
        "Reconnecting…": "正在重新连接…",
        "Rename Current Speaker…": "重命名当前说话人…",
        "Rename speaker": "重命名说话人",
        "Resume": "继续",
        "Same person as…": "与…是同一人",
        "Save": "保存",
        "Settings…": "设置…",
        "Shortcuts": "快捷键",
        "Show Captions": "显示字幕",
        "Show Original": "显示原文",
        "Show Transcript": "显示记录",
        "Smaller Text": "缩小文字",
        "Soniox didn’t accept the settings: %@": "Soniox 不接受当前设置：%@",
        "Soniox is rate limiting this key. Try again in a moment.": "请求过于频繁，请稍后再试。",
        "Soniox rejected the API key.": "Soniox 拒绝了此 API 密钥。",
        "Speaker %d": "说话人 %d",
        "Speakers": "说话人",
        "Speakers appear here as they talk.": "说话人发言后会显示在这里。",
        "Speech in any language is translated into one language.": "任何语言的讲话都会翻译成同一种语言。",
        "Start / Pause": "开始 / 暂停",
        "Start Listening": "开始收听",
        "Style": "样式",
        "Luka listens to your Mac and writes down every speaker, translated as they talk.": "Luka 收听 Mac 上的声音，按说话人实时记录并翻译。",
        "System": "跟随系统",
        "Text size": "文字大小",
        "To": "目标语言",
        "Transcribe": "转写",
        "Transcript": "记录",
        "Translate": "翻译",
        "Try Again": "重试",
        "Two-way": "双向",
        "Writes down what’s said, without translating.": "只转写内容，不翻译。",
        "Your Soniox account is out of credits.": "Soniox 账户余额不足。",
        "Back to Live Session": "回到实时会话",
        "Continue": "继续收听",
        "Copied transcript": "已复制记录",
        "Copy Transcript": "复制记录",
        "Delete": "删除",
        "Delete Line": "删除此行",
        "Delete Session…": "删除会话…",
        "Delete this session?": "要删除这个会话吗？",
        "Delete…": "删除…",
        "Edit": "编辑",
        "Edit transcript": "编辑记录",
        "Finish Session": "结束会话",
        "Finish the session to edit": "结束会话后即可编辑",
        "In Luka": "在 Luka 中",
        "Lock / unlock captions": "锁定 / 解锁字幕",
        "Luka keeps running in the menu bar, so ⌃⌥N can start a transcription at any time.": "Luka 会在菜单栏中持续运行，随时按 ⌃⌥N 即可开始转写。",
        "More": "更多",
        "Name whoever is speaking": "为正在说话的人命名",
        "New Transcription": "新建转写",
        "New transcription": "新建转写",
        "No Session": "没有会话",
        "Nothing yet": "暂无内容",
        "Open at login": "登录时打开",
        "Open transcript": "打开记录",
        "Rename…": "重命名…",
        "Show / hide captions": "显示 / 隐藏字幕",
        "Show / hide transcript": "显示 / 隐藏记录",
        "Show in Dock": "在程序坞中显示",
        "The transcript will be removed from this Mac.": "记录将从这台 Mac 上删除。",
        "Title": "标题",
        "Today": "今天",
        "Unlock": "解锁",
        "Works from any app": "在任意应用中可用",
        "Yesterday": "昨天",
        "from any app": "在任意应用中",
        "Swap": "互换",
        "Show captions": "显示字幕",
        "While listening": "仅在收听时",
        "Always": "始终",
        "Captions fade in when Luka starts listening and out when you finish. ⌃⌥C hides or shows them anytime.": "开始收听时字幕淡入，结束后淡出。随时可按 ⌃⌥C 隐藏或显示。",
        "Captions stay until you hide them with ⌃⌥C.": "字幕会一直显示，直到按 ⌃⌥C 隐藏。",
    ]
}
